export const fbankdata = {
  status: true,
  message: "Request Completed",
  data: [
    {
      id: 86,
      activeFlag: 1,
      bankName: "Last Used Bank",
      details: "Last Used Bank",
      remarks: "NULL",
      timestamp: "17/07/2017 12:58:00",
      iinno: "NULL",
    },
    {
      id: 112,
      activeFlag: 1,
      bankName: "Airtel Payment Bank",
      details: "Airtel Payment Bank",
      remarks: null,
      timestamp: "01/08/2019 16:56:00",
      iinno: "990320",
    },
    {
      id: 33,
      activeFlag: 1,
      bankName: "Andhra Pradesh Grameena Vikash Bank",
      details: "Andhra Pradesh Grameena Vikash Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607198",
    },
    {
      id: 34,
      activeFlag: 1,
      bankName: "Andhra Pragathi Grameena Bank",
      details: "Andhra Pragathi Grameena Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607121",
    },
    {
      id: 108,
      activeFlag: 1,
      bankName: "AP Mahesh Coop Urban Bank Ltd",
      details: "AP Mahesh Coop Urban Bank Ltd",
      remarks: null,
      timestamp: "02/05/2019 12:00:00",
      iinno: "607051",
    },
    {
      id: 47,
      activeFlag: 1,
      bankName: "Aryavart Bank erstwhile Gramin Bank of Aryavart",
      details: "Gramin bank of Aryavart",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607024",
    },
    {
      id: 35,
      activeFlag: 1,
      bankName: "Assam Gramin Vikash Bank",
      details: "Assam Gramin Vikash Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607064",
    },
    {
      id: 110,
      activeFlag: 1,
      bankName: "AU Small Finance Bank",
      details: "AU Small Finance Bank",
      remarks: null,
      timestamp: "02/05/2019 12:00:00",
      iinno: "608087",
    },
    {
      id: 10,
      activeFlag: 1,
      bankName: "Axis Bank",
      details: "Axis Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607153",
    },
    {
      id: 36,
      activeFlag: 1,
      bankName: "Bangiya Gramin Vikash Bank",
      details: "Bangiya Gramin Vikash Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607063",
    },
    {
      id: 19,
      activeFlag: 1,
      bankName: "Bank Of Baroda ertswhile Vijaya Bank erstwhile Dena Bank",
      details: "Bank Of Baroda",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "606985",
    },
    {
      id: 2,
      activeFlag: 1,
      bankName: "Bank of India",
      details: "Bank of India",
      remarks: "",
      timestamp: "21/11/2016 16:00:00",
      iinno: "508505",
    },
    {
      id: 11,
      activeFlag: 1,
      bankName: "Bank of Maharashtra",
      details: "Bank of Maharashtra",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607387",
    },
    {
      id: 37,
      activeFlag: 1,
      bankName: "Baroda Gujarat Gramin Bank",
      details: "Baroda Gujarat Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "606995",
    },
    {
      id: 38,
      activeFlag: 1,
      bankName: "Baroda Rajasthan Kshetriya Gramin Bank",
      details: "Baroda Rajasthan Kshetriya Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607280",
    },
    {
      id: 39,
      activeFlag: 1,
      bankName: "Baroda Uttar Pradesh Gramin Bank ",
      details: "Baroda Uttar Pradesh Gramin Bank ",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "606993",
    },
    {
      id: 182,
      activeFlag: 1,
      bankName: "Bhandara Dist Coop Bank",
      details: "Bhandara Dist Coop Bank",
      remarks: null,
      timestamp: "04/09/2023 16:26:00",
      iinno: "607847",
    },
    {
      id: 4,
      activeFlag: 1,
      bankName: "Canara Bank erstwhile Syndicate Bank",
      details: "Canara Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607396",
    },
    {
      id: 107,
      activeFlag: 1,
      bankName: "Catholic Syrian Bank",
      details: "Catholic Syrian Bank",
      remarks: null,
      timestamp: "02/05/2019 12:00:00",
      iinno: "607082",
    },
    {
      id: 9,
      activeFlag: 1,
      bankName: "Central Bank of India",
      details: "Central Bank of India",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607264",
    },
    {
      id: 43,
      activeFlag: 1,
      bankName: "Chaitanya Godavari Gramin Bank",
      details: "Chaitanya Godavari Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607080",
    },
    {
      id: 140,
      activeFlag: 1,
      bankName: "CHENNAI CENTRAL CO-OPERATIVE BANK LTD.",
      details: "CHENNAI CENTRAL CO-OPERATIVE BANK LTD.",
      remarks: null,
      timestamp: null,
      iinno: "508664",
    },
    {
      id: 44,
      activeFlag: 1,
      bankName: "Chhattisgarh Rajya Gramin Bank",
      details: "Chhattisgarh Rajya Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607214",
    },
    {
      id: 93,
      activeFlag: 1,
      bankName: "City Union Bank ",
      details: "City Union Bank ",
      remarks: "NULL",
      timestamp: "03/11/2017 03:49:00",
      iinno: "607324",
    },
    {
      id: 135,
      activeFlag: 1,
      bankName: "Dharmapuri District Central Co op Bank Ltd",
      details: "Dharmapuri District Central Co op Bank Ltd",
      remarks: null,
      timestamp: "21/01/2021 16:40:00",
      iinno: "508658",
    },
    {
      id: 143,
      activeFlag: 1,
      bankName: "Dindigul Central Co-operative Bank Ltd",
      details: "Dindigul Central Co-operative Bank Ltd",
      remarks: null,
      timestamp: null,
      iinno: "508659",
    },
    {
      id: 46,
      activeFlag: 1,
      bankName: "Ellaquai Dehati Bank",
      details: "Ellaquai Dehati Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607218",
    },
    {
      id: 102,
      activeFlag: 1,
      bankName: "Equitas Small Finance Bank",
      details: "Equitas Small Finance Bank",
      remarks: null,
      timestamp: "15/05/2018 11:25:00",
      iinno: "508998",
    },
    {
      id: 125,
      activeFlag: 1,
      bankName: "Erode District Central Co-operative Bank",
      details: "Erode District Central Co-operative Bank",
      remarks: null,
      timestamp: "26/10/2020 14:16:00",
      iinno: "508654",
    },
    {
      id: 122,
      activeFlag: 1,
      bankName: "ESAF Small Finance Bank",
      details: "ESAF Small Finance Bank",
      remarks: null,
      timestamp: "24/09/2020 17:28:00",
      iinno: "652254",
    },
    {
      id: 15,
      activeFlag: 1,
      bankName: "Federal Bank",
      details: "Federal Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607363",
    },
    {
      id: 118,
      activeFlag: 1,
      bankName: "Fincare Small Finance Bank",
      details: "Fincare Small Finance Bank",
      remarks: null,
      timestamp: "03/04/2020 18:58:00",
      iinno: "817304",
    },
    {
      id: 95,
      activeFlag: 1,
      bankName: "Fino Payments Bank",
      details: "Fino Payments Bank",
      remarks: "NULL",
      timestamp: "03/11/2017 03:49:00",
      iinno: "608001",
    },
    {
      id: 31,
      activeFlag: 1,
      bankName: "HDFC Bank",
      details: "HDFC Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607152",
    },
    {
      id: 48,
      activeFlag: 1,
      bankName: "Himachal Pradesh Gramin Bank",
      details: "Himachal Pradesh Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607140",
    },
    {
      id: 5,
      activeFlag: 1,
      bankName: "ICICI Bank",
      details: "ICICI Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "508534",
    },
    {
      id: 166,
      activeFlag: 1,
      bankName: "ICICI Onus",
      details: "ICICI",
      remarks: null,
      timestamp: null,
      iinno: "000015",
    },
    {
      id: 165,
      activeFlag: 1,
      bankName: "ICICI TEST",
      details: "ICICI",
      remarks: null,
      timestamp: null,
      iinno: "100032",
    },
    {
      id: 14,
      activeFlag: 1,
      bankName: "IDBI Bank",
      details: "IDBI Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607095",
    },
    {
      id: 49,
      activeFlag: 1,
      bankName: "IDFC First Bank",
      details: "IDFC First Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "608117",
    },
    {
      id: 113,
      activeFlag: 1,
      bankName: "India Post Payment Bank",
      details: "India Post Payment Bank",
      remarks: null,
      timestamp: "13/09/2019 12:26:00",
      iinno: "608314",
    },
    {
      id: 18,
      activeFlag: 1,
      bankName: "Indian bank erstwhile Allahabad Bank",
      details: "Indian bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607105",
    },
    {
      id: 25,
      activeFlag: 1,
      bankName: "Indian Overseas Bank",
      details: "Indian Overseas Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607126",
    },
    {
      id: 32,
      activeFlag: 1,
      bankName: "IndusInd Bank",
      details: "IndusInd Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607189",
    },
    {
      id: 120,
      activeFlag: 1,
      bankName: "J& K Grameen Bank",
      details: "J& K Grameen Bank",
      remarks: null,
      timestamp: "15/07/2020 17:25:00",
      iinno: "607808",
    },
    {
      id: 50,
      activeFlag: 1,
      bankName: "Jammu & Kashmir Bank ",
      details: "Jammu & Kashmir Bank ",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607440",
    },
    {
      id: 183,
      activeFlag: 1,
      bankName: "Jana Small Finance Bank Ltd.",
      details: "Jana Small Finance Bank Ltd.",
      remarks: null,
      timestamp: "04/09/2023 16:26:00",
      iinno: "508910",
    },
    {
      id: 83,
      activeFlag: 1,
      bankName: "Jharkhand Rajya Gramin Bank erstwhile Vananchal Gramin Bank",
      details: "Jharkhand Rajya Gramin Bank erstwhile Vananchal Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607210",
    },
    {
      id: 178,
      activeFlag: 1,
      bankName: "Jio Payments Bank Limited",
      details: "Jio Payments Bank Limited",
      remarks: null,
      timestamp: "04/09/2023 16:26:00",
      iinno: "607884",
    },
    {
      id: 144,
      activeFlag: 1,
      bankName: "KANCHEEPURAM CENTRAL COOPERATIVE BANK",
      details: "KANCHEEPURAM CENTRAL COOPERATIVE BANK",
      remarks: null,
      timestamp: null,
      iinno: "508734",
    },
    {
      id: 96,
      activeFlag: 1,
      bankName: "Karnataka Bank",
      details: "Karnataka Bank",
      remarks: "NULL",
      timestamp: "03/11/2017 03:49:00",
      iinno: "607270",
    },
    {
      id: 65,
      activeFlag: 1,
      bankName: "Karnataka Gramin Bank erstwhile Pragathi Krishna Gramin Bank",
      details: "Karnataka Gramin Bank erstwhile Pragathi Krishna Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607400",
    },
    {
      id: 52,
      activeFlag: 1,
      bankName: "Karnataka Vikas Grameena Bank ",
      details: "Karnataka Vikas Grameena Bank ",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607122",
    },
    {
      id: 53,
      activeFlag: 1,
      bankName: "Karur Vysya Bank",
      details: "Karur Vysya Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "508662",
    },
    {
      id: 92,
      activeFlag: 1,
      bankName: "Kashi Gomati Samyut Gramin Bank",
      details: "Kashi Gomati Samyut Gramin Bank",
      remarks: "NULL",
      timestamp: "03/11/2017 03:49:00",
      iinno: "607365",
    },
    {
      id: 54,
      activeFlag: 1,
      bankName: "Kerala Gramin Bank",
      details: "Kerala Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607399",
    },
    {
      id: 100,
      activeFlag: 1,
      bankName: "Kotak Mahindra Bank",
      details: "Kotak Mahindra Bank",
      remarks: "",
      timestamp: "25/04/2018 13:29:00",
      iinno: "990309",
    },
    {
      id: 106,
      activeFlag: 1,
      bankName: "Lakshmi Vilas Bank",
      details: "Lakshmi Vilas Bank",
      remarks: null,
      timestamp: "07/09/2018 15:25:00",
      iinno: "607058",
    },
    {
      id: 56,
      activeFlag: 1,
      bankName: "Madhya Bihar Gramin Bank erstwhile Dakshin Bihar Gramin Bank",
      details: "Madhya Bihar Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607136",
    },
    {
      id: 61,
      activeFlag: 1,
      bankName:
        "Madhya Pradesh Gramin Bank erstwhile Narmada Jhabua Gramin Bank",
      details: "Narmada Jhabua Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607022",
    },
    {
      id: 57,
      activeFlag: 1,
      bankName: "Madhyanchal Gramin Bank",
      details: "Madhyanchal Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607232",
    },
    {
      id: 90,
      activeFlag: 1,
      bankName: "Maharashtra Gramin Bank ",
      details: "Maharashtra Gramin Bank ",
      remarks: "NULL",
      timestamp: "03/11/2017 03:49:00",
      iinno: "607000",
    },
    {
      id: 162,
      activeFlag: 1,
      bankName: "Maharashtra State Co-operative Bank",
      details: "Maharashtra State Co-operative Bank",
      remarks: null,
      timestamp: null,
      iinno: "607315",
    },
    {
      id: 59,
      activeFlag: 1,
      bankName: "Manipur Rural Bank ",
      details: "Manipur Rural Bank ",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607062",
    },
    {
      id: 189,
      activeFlag: 1,
      bankName: "Mayurbhanj Central Co-operative Bank Ltd",
      details: "Mayurbhanj Central Co-operative Bank Ltd",
      remarks: null,
      timestamp: "04/09/2023 16:26:00",
      iinno: "508756",
    },
    {
      id: 60,
      activeFlag: 1,
      bankName: "Meghalaya Rural Bank",
      details: "Meghalaya Rural Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607206",
    },
    {
      id: 117,
      activeFlag: 1,
      bankName: "Mizoram Rural Bank",
      details: "Mizoram Rural Bank",
      remarks: null,
      timestamp: "22/01/2020 18:47:00",
      iinno: "607230",
    },
    {
      id: 150,
      activeFlag: 1,
      bankName: "NSDL Payments Bank Limited ",
      details: "NSDL Payments Bank Limited ",
      remarks: null,
      timestamp: null,
      iinno: "607768",
    },
    {
      id: 62,
      activeFlag: 1,
      bankName: "Odisha Gramya Bank ",
      details: "Odisha Gramya Bank ",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607060",
    },
    {
      id: 179,
      activeFlag: 1,
      bankName: "Odisha State Co-Operative Bank",
      details: "Odisha State Co-Operative Bank",
      remarks: null,
      timestamp: "04/09/2023 16:26:00",
      iinno: "607935",
    },
    {
      id: 89,
      activeFlag: 1,
      bankName: "Paschim Banga Gramin Bank",
      details: "Paschim Banga Gramin Bank",
      remarks: "NULL",
      timestamp: "03/11/2017 03:49:00",
      iinno: "607079",
    },
    {
      id: 121,
      activeFlag: 1,
      bankName: "Paytm Payments Bank",
      details: "Paytm Payments Bank",
      remarks: null,
      timestamp: "23/07/2020 18:12:00",
      iinno: "608032",
    },
    {
      id: 66,
      activeFlag: 1,
      bankName: "Prathma UP Gramin Bank erstwhile Sarva UP Gramin Bank ",
      details: "Prathma UP Gramin Bank erstwhile Sarva UP Gramin Bank ",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607135",
    },
    {
      id: 153,
      activeFlag: 1,
      bankName: "PTEST",
      details: "PTEST",
      remarks: null,
      timestamp: null,
      iinno: "100141",
    },
    {
      id: 146,
      activeFlag: 1,
      bankName: "Pudukottai District Central Cooperative Bank Ltd",
      details: "Pudukottai District Central Cooperative Bank Ltd",
      remarks: null,
      timestamp: null,
      iinno: "508656",
    },
    {
      id: 88,
      activeFlag: 1,
      bankName: "Puduvai Bharathiar Grama Bank",
      details: "Puduvai Bharathiar Grama Bank",
      remarks: "NULL",
      timestamp: "03/11/2017 03:49:00",
      iinno: "607054",
    },
    {
      id: 28,
      activeFlag: 1,
      bankName: "Punjab & Sind Bank",
      details: "Punjab & Sind Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607087",
    },
    {
      id: 67,
      activeFlag: 1,
      bankName: "Punjab Gramin Bank",
      details: "Punjab Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607138",
    },
    {
      id: 7,
      activeFlag: 1,
      bankName: "Punjab National Bank erstwhile Oriental Bank of Commerce",
      details: "Punjab National Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607027",
    },
    {
      id: 68,
      activeFlag: 1,
      bankName: "Purvanchal Gramin Bank",
      details: "Purvanchal Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607212",
    },
    {
      id: 69,
      activeFlag: 1,
      bankName: "Rajasthan Marudhara Gramin Bank",
      details: "Rajasthan Marudhara Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607509",
    },
    {
      id: 181,
      activeFlag: 1,
      bankName: "Rajasthan State Coop Bank",
      details: "Rajasthan State Coop Bank",
      remarks: null,
      timestamp: "04/09/2023 16:26:00",
      iinno: "607266",
    },
    {
      id: 70,
      activeFlag: 1,
      bankName: "Ratnakar Bank",
      details: "Ratnakar Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607393",
    },
    {
      id: 71,
      activeFlag: 1,
      bankName: "Saptagiri Grameena Bank",
      details: "Saptagiri Grameena Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607053",
    },
    {
      id: 72,
      activeFlag: 1,
      bankName: "Sarva Haryana Gramin Bank",
      details: "Sarva Haryana Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607139",
    },
    {
      id: 74,
      activeFlag: 1,
      bankName: "Saurashtra Gramin Bank",
      details: "Saurashtra Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607200",
    },
    {
      id: 123,
      activeFlag: 1,
      bankName: "SBM Bank (INDIA) Limited",
      details: "SBM Bank (INDIA) Limited",
      remarks: null,
      timestamp: "26/10/2020 14:16:00",
      iinno: "607395",
    },
    {
      id: 97,
      activeFlag: 1,
      bankName: "Shivalik Mercantile Cooperative Bank ",
      details: "Shivalik Mercantile Cooperative Bank ",
      remarks: "NULL",
      timestamp: "03/11/2017 03:49:00",
      iinno: "607119",
    },
    {
      id: 13,
      activeFlag: 1,
      bankName: "South Indian Bank",
      details: "South Indian Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607439",
    },
    {
      id: 6,
      activeFlag: 1,
      bankName: "State Bank of India",
      details: "State Bank of India",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607094",
    },
    {
      id: 124,
      activeFlag: 1,
      bankName: "Suryoday Small Fianance Bank",
      details: "Suryoday Small Fianance Bank",
      remarks: null,
      timestamp: "26/10/2020 14:16:00",
      iinno: "608022",
    },
    {
      id: 119,
      activeFlag: 1,
      bankName: "Tamil Nadu State Apex Co-operative Bank Ltd",
      details: "Tamil Nadu State Apex Co-operative Bank Ltd",
      remarks: null,
      timestamp: "04/06/2020 20:27:00",
      iinno: "607131",
    },
    {
      id: 98,
      activeFlag: 1,
      bankName: "Tamilnad Mercantile Bank",
      details: "Tamilnad Mercantile Bank",
      remarks: "NULL",
      timestamp: "03/11/2017 03:49:00",
      iinno: "607187",
    },
    {
      id: 63,
      activeFlag: 1,
      bankName: "TamilNadu Grama Bank erstwhile Pallavan Grama Bank",
      details: "TamilNadu Grama Bank erstwhile Pallavan Grama Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607052",
    },
    {
      id: 77,
      activeFlag: 1,
      bankName: "Telangana Grameena Bank",
      details: "Telangana Grameena Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607195",
    },
    {
      id: 141,
      activeFlag: 1,
      bankName: "Thanjavur Central Co op Bank Ltd",
      details: "Thanjavur Central Co op Bank Ltd",
      remarks: null,
      timestamp: null,
      iinno: "508665",
    },
    {
      id: 184,
      activeFlag: 1,
      bankName: "The Balasore Bhadrak Central Co-Op. Bank Ltd",
      details: "The Balasore Bhadrak Central Co-Op. Bank Ltd",
      remarks: null,
      timestamp: "04/09/2023 16:26:00",
      iinno: "508758",
    },
    {
      id: 190,
      activeFlag: 1,
      bankName: "The Banki Central Co-operative Bank Ltd",
      details: "The Banki Central Co-operative Bank Ltd",
      remarks: null,
      timestamp: "04/09/2023 16:26:00",
      iinno: "508761",
    },
    {
      id: 127,
      activeFlag: 1,
      bankName: "The Coimbatore District Central Co-op Bank Limited",
      details: "The Coimbatore District Central Co-op Bank Limited",
      remarks: null,
      timestamp: "21/01/2021 16:40:00",
      iinno: "508646",
    },
    {
      id: 105,
      activeFlag: 1,
      bankName: "THE Cosmos Co-operative Bank Ltd",
      details: "HE Cosmos Co-operative Bank Ltd",
      remarks: null,
      timestamp: "07/09/2018 15:25:00",
      iinno: "608194",
    },
    {
      id: 128,
      activeFlag: 1,
      bankName: "THE CUDDALORE DISTRICT CENTRAL COOPERATIVE BANK",
      details: "THE CUDDALORE DISTRICT CENTRAL COOPERATIVE BANK",
      remarks: null,
      timestamp: "21/01/2021 16:40:00",
      iinno: "508647",
    },
    {
      id: 151,
      activeFlag: 1,
      bankName: "THE GAYATRI COOPERATIVE URBAN BANK LTD",
      details: "THE GAYATRI COOPERATIVE URBAN BANK LTD",
      remarks: null,
      timestamp: null,
      iinno: "607157",
    },
    {
      id: 129,
      activeFlag: 1,
      bankName: "The Kanyakumari District Central Cooperative Bank",
      details: "The Kanyakumari District Central Cooperative Bank",
      remarks: null,
      timestamp: "21/01/2021 16:40:00",
      iinno: "508655",
    },
    {
      id: 186,
      activeFlag: 1,
      bankName: "The Khordha Central Co-Op. Bank Ltd.",
      details: "The Khordha Central Co-Op. Bank Ltd.",
      remarks: null,
      timestamp: "04/09/2023 16:26:00",
      iinno: "508771",
    },
    {
      id: 130,
      activeFlag: 1,
      bankName: "The Kumbakonam Central Co-operative Bank Ltd",
      details: "The Kumbakonam Central Co-operative Bank Ltd",
      remarks: null,
      timestamp: "21/01/2021 16:40:00",
      iinno: "508720",
    },
    {
      id: 137,
      activeFlag: 1,
      bankName: "The Madurai District Central Cooperative Bank Ltd",
      details: "The Madurai District Central Cooperative Bank Ltd",
      remarks: null,
      timestamp: null,
      iinno: "508681",
    },
    {
      id: 145,
      activeFlag: 1,
      bankName: "The Nilgiris District Central Coop Bank Ltd",
      details: "The Nilgiris District Central Coop Bank Ltd",
      remarks: null,
      timestamp: null,
      iinno: "508660",
    },
    {
      id: 138,
      activeFlag: 1,
      bankName: "The Ramanathapuram District Central Co op Bank Ltd",
      details: "The Ramanathapuram District Central Co op Bank Ltd",
      remarks: null,
      timestamp: null,
      iinno: "508676",
    },
    {
      id: 136,
      activeFlag: 1,
      bankName: "THE SALEM DISTRICT CENTRAL CO-OPERATIVE BANK LTD",
      details: "THE SALEM DISTRICT CENTRAL CO-OPERATIVE BANK LTD",
      remarks: null,
      timestamp: null,
      iinno: "508648",
    },
    {
      id: 99,
      activeFlag: 1,
      bankName: "The Saraswat Co-operative Bank Ltd",
      details: "The Saraswat Co-operative Bank Ltd",
      remarks: "NULL",
      timestamp: "03/11/2017 03:49:00",
      iinno: "652150",
    },
    {
      id: 187,
      activeFlag: 1,
      bankName: "The Sundargarh District Central Co-Op. Bank Ltd",
      details: "The Sundargarh District Central Co-Op. Bank Ltd",
      remarks: null,
      timestamp: "04/09/2023 16:26:00",
      iinno: "508757",
    },
    {
      id: 131,
      activeFlag: 1,
      bankName: "The Thoothukudi District Central Coop Bank Ltd",
      details: "The Thoothukudi District Central Coop Bank Ltd",
      remarks: null,
      timestamp: "21/01/2021 16:40:00",
      iinno: "508678",
    },
    {
      id: 147,
      activeFlag: 1,
      bankName: "THE TIRUCHIRAPALLI DIST. CENT COOPERATIVE BANK LTD",
      details: "THE TIRUCHIRAPALLI DIST. CENT COOPERATIVE BANK LTD",
      remarks: null,
      timestamp: null,
      iinno: "508680",
    },
    {
      id: 132,
      activeFlag: 1,
      bankName: "The Tirunelveli District Central Co-op Bank Ltd",
      details: "The Tirunelveli District Central Co-op Bank Ltd",
      remarks: null,
      timestamp: "21/01/2021 16:40:00",
      iinno: "508677",
    },
    {
      id: 139,
      activeFlag: 1,
      bankName: "The Tiruvannamalai District Central Coop Bank Ltd",
      details: "The Tiruvannamalai District Central Coop Bank Ltd",
      remarks: null,
      timestamp: null,
      iinno: "508657",
    },
    {
      id: 185,
      activeFlag: 1,
      bankName: "The United Puri-Nimpara Central Co-Op. Bank Ltd",
      details: "The United Puri-Nimpara Central Co-Op. Bank Ltd",
      remarks: null,
      timestamp: "04/09/2023 16:26:00",
      iinno: "508782",
    },
    {
      id: 133,
      activeFlag: 1,
      bankName: "THE VELLORE DISTRICT CENTRAL CO-OP BANK LTD.",
      details: "THE VELLORE DISTRICT CENTRAL CO-OP BANK LTD.",
      remarks: null,
      timestamp: "21/01/2021 16:40:00",
      iinno: "508679",
    },
    {
      id: 134,
      activeFlag: 1,
      bankName: "THE VILLUPURAM DISTRICT CENTRAL CO-OP BANK LTD",
      details: "THE VILLUPURAM DISTRICT CENTRAL CO-OP BANK LTD",
      remarks: null,
      timestamp: "21/01/2021 16:40:00",
      iinno: "508737",
    },
    {
      id: 142,
      activeFlag: 1,
      bankName: "The Virudhunagar District Central Co-op Bank Ltd",
      details: "The Virudhunagar District Central Co-op Bank Ltd",
      remarks: null,
      timestamp: null,
      iinno: "508732",
    },
    {
      id: 148,
      activeFlag: 1,
      bankName: "THE SIVAGANGAI DISTRICT CENTRAL COOP BANK LTD",
      details: "THE SIVAGANGAI DISTRICT CENTRAL COOP BANK LTD",
      remarks: null,
      timestamp: null,
      iinno: "508649",
    },
    {
      id: 78,
      activeFlag: 1,
      bankName: "Tripura Gramin Bank",
      details: "Tripura Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607065",
    },
    {
      id: 149,
      activeFlag: 1,
      bankName: "Tripura State Co-operative Bank Ltd.",
      details: "Tripura State Co-operative Bank Ltd.",
      remarks: null,
      timestamp: null,
      iinno: "607978",
    },
    {
      id: 20,
      activeFlag: 1,
      bankName: "UCO Bank",
      details: "UCO Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607066",
    },
    {
      id: 109,
      activeFlag: 1,
      bankName: "Ujjivan Small Finance Bank Limited",
      details: "Ujjivan Small Finance Bank Limited",
      remarks: null,
      timestamp: "02/05/2019 12:00:00",
      iinno: "508991",
    },
    {
      id: 1,
      activeFlag: 1,
      bankName:
        "Union Bank of India erstwhile Corporation Bank erstwhile Andhra Bank",
      details: "Union Bank of India",
      remarks: "",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607161",
    },
    {
      id: 180,
      activeFlag: 1,
      bankName: "Up State Coop Bank",
      details: "Up State Coop Bank",
      remarks: null,
      timestamp: "04/09/2023 16:26:00",
      iinno: "607523",
    },
    {
      id: 79,
      activeFlag: 1,
      bankName: "Utkal Gramin Bank",
      details: "Utkal Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607234",
    },
    {
      id: 188,
      activeFlag: 1,
      bankName: "Utkarsh Small Finance Bank Ltd",
      details: "Utkarsh Small Finance Bank Ltd",
      remarks: null,
      timestamp: "04/09/2023 16:26:00",
      iinno: "608014",
    },
    {
      id: 80,
      activeFlag: 1,
      bankName: "Uttar Banga Kshetriya Gramin Bank ",
      details: "Uttar Banga Kshetriya Gramin Bank ",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607073",
    },
    {
      id: 81,
      activeFlag: 1,
      bankName: "Uttar Bihar Grameen Bank ",
      details: "Uttar Bihar Grameen Bank ",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607069",
    },
    {
      id: 82,
      activeFlag: 1,
      bankName: "Uttarakhand Gramin Bank",
      details: "Uttarakhand Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607197",
    },
    {
      id: 84,
      activeFlag: 1,
      bankName: "Vidarbha Konkan Gramin Bank",
      details: "Vidarbha Konkan Gramin Bank",
      remarks: "NULL",
      timestamp: "21/11/2016 16:00:00",
      iinno: "607020",
    },
    {
      id: 104,
      activeFlag: 1,
      bankName: "YES Bank",
      details: "YES Bank",
      remarks: null,
      timestamp: "15/05/2018 11:25:00",
      iinno: "607618",
    },
    {
      id: 154,
      activeFlag: 1,
      bankName: "ZKotak Bank 000013",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "000013",
    },
    {
      id: 161,
      activeFlag: 1,
      bankName: "ZKotak Bank 000014",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "000014",
    },
    {
      id: 160,
      activeFlag: 1,
      bankName: "ZKotak Bank 000015",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "000015",
    },
    {
      id: 152,
      activeFlag: 1,
      bankName: "ZKotak Bank 000016",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "000016",
    },
    {
      id: 168,
      activeFlag: 1,
      bankName: "ZKotak Bank 000018",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "000018",
    },
    {
      id: 163,
      activeFlag: 1,
      bankName: "ZKotak Bank 000032",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "000032",
    },
    {
      id: 164,
      activeFlag: 1,
      bankName: "ZKotak Bank 000039",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "000039",
    },
    {
      id: 175,
      activeFlag: 1,
      bankName: "ZKotak Bank 100001",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "100001",
    },
    {
      id: 177,
      activeFlag: 1,
      bankName: "Zkotak Bank 100011",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "100011",
    },
    {
      id: 169,
      activeFlag: 1,
      bankName: "ZKotak Bank 100012",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "100012",
    },
    {
      id: 155,
      activeFlag: 1,
      bankName: "ZKotak Bank 100013",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "100013",
    },
    {
      id: 170,
      activeFlag: 1,
      bankName: "ZKotak Bank 100014",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "100014",
    },
    {
      id: 171,
      activeFlag: 1,
      bankName: "ZKotak Bank 100022",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "100022",
    },
    {
      id: 172,
      activeFlag: 1,
      bankName: "ZKotak Bank 100024",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "100024",
    },
    {
      id: 173,
      activeFlag: 1,
      bankName: "ZKotak Bank 100026",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "100026",
    },
    {
      id: 174,
      activeFlag: 1,
      bankName: "ZKotak Bank 100028",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "100028",
    },
    {
      id: 176,
      activeFlag: 1,
      bankName: "ZKotak Bank 100031",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "100031",
    },
    {
      id: 156,
      activeFlag: 1,
      bankName: "ZKotak Bank 100033",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "100033",
    },
    {
      id: 159,
      activeFlag: 1,
      bankName: "ZKotak Bank 100034",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "100034",
    },
    {
      id: 158,
      activeFlag: 1,
      bankName: "ZKotak Bank 100051",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "100051",
    },
    {
      id: 157,
      activeFlag: 1,
      bankName: "ZKotak Bank 100452",
      details: "KTEST",
      remarks: null,
      timestamp: null,
      iinno: "100452",
    },
  ],
  statusCode: 0,
};
