export const data = {
  BondType: "OutBound",
  Bonds: [
    {
      BoundType: "OutBound",
      IsBaggageFare: false,
      IsSSR: false,
      ItineraryKey: null,
      JourneyTime: "18h 10m",
      Legs: [
        {
          AircraftCode: "",
          AircraftType: "320",
          AirlineName: "UK",
          AirlinePnr: null,
          ArrivalDate: "Tue-12Sep2023",
          ArrivalTerminal: "1",
          ArrivalTime: "20:20",
          AvailableSeat: "9",
          BaggageUnit: "Kgs",
          BaggageWeight: "15",
          BookSeat: null,
          BoundType: "OutBound",
          Cabin: "Economy",
          CabinBagUT: "Kgs",
          CabinBagWT: "7",
          CabinClasses: null,
          Capacity: 0,
          CarrierCode: "UK",
          CurrencyCode: "INR",
          DepartureDate: "Tue-12Sep2023",
          DepartureTerminal: "3",
          DepartureTime: "17:35",
          Destination: "MAA",
          Duration: "02h 45m",
          FareBasisCode: "VL1PYS",
          FareClassOfService: "V",
          FareRulesKey: null,
          FlightDesignator: null,
          FlightDetailRefKey: "",
          FlightName: "Vistara",
          FlightNumber: "837",
          GDSPnr: null,
          Group: "0",
          IsConnecting: false,
          IsSeatOpen: false,
          LayoverArrDT: null,
          LayoverAt: null,
          LayoverDepDT: null,
          LayoverDuration: null,
          NumberOfStops: "0",
          OpenSegment: false,
          OperatedBy: null,
          Origin: "DEL",
          ProviderCode:
            "1G!`320`1`9`Kgs`15`Economy``UK`3`0`False`0``````02h 45m`VL1PYS`V",
          Remarks: "",
          SSRDetails: null,
          Sold: 0,
          Status: null,
        },
        {
          AircraftCode: "",
          AircraftType: "320",
          AirlineName: "UK",
          AirlinePnr: null,
          ArrivalDate: "Wed-13Sep2023",
          ArrivalTerminal: "2",
          ArrivalTime: "11:45",
          AvailableSeat: "9",
          BaggageUnit: "Kgs",
          BaggageWeight: "15",
          BookSeat: null,
          BoundType: "OutBound",
          Cabin: "Economy",
          CabinBagUT: "Kgs",
          CabinBagWT: "7",
          CabinClasses: null,
          Capacity: 0,
          CarrierCode: "UK",
          CurrencyCode: "INR",
          DepartureDate: "Wed-13Sep2023",
          DepartureTerminal: "1",
          DepartureTime: "09:40",
          Destination: "BOM",
          Duration: "02h 05m",
          FareBasisCode: "VL1PYS",
          FareClassOfService: "V",
          FareRulesKey: null,
          FlightDesignator: null,
          FlightDetailRefKey: "",
          FlightName: "Vistara",
          FlightNumber: "822",
          GDSPnr: null,
          Group: "0",
          IsConnecting: false,
          IsSeatOpen: false,
          LayoverArrDT: null,
          LayoverAt: null,
          LayoverDepDT: null,
          LayoverDuration: null,
          NumberOfStops: "0",
          OpenSegment: false,
          OperatedBy: null,
          Origin: "MAA",
          ProviderCode:
            "1G!`320`2`9`Kgs`15`Economy``UK`1`0`False`0``````02h 05m`VL1PYS`V",
          Remarks: "",
          SSRDetails: null,
          Sold: 0,
          Status: null,
        },
      ],
      addOnDetail: null,
    },
  ],
  CurrencyCode: "INR",
  Deeplink: "",
  EngineID: 7,
  ExtSeatAvailStatus: false,
  Fare: {
    BasicFare: 11320,
    BrandKeys: null,
    DiscountValue: 0,
    DueAmount: 0,
    ExchangeRate: 0,
    FareName: 1,
    OfferedFare: 0,
    PNRAmount: 0,
    PaxFares: [
      {
        AdminMarkUP: 0,
        AirlinePnr: null,
        BaggageUnit: "Kgs",
        BaggageWeight: "15",
        BaseTransactionAmount: 0,
        BasicFare: 11320,
        Branded: null,
        CDValue: 0,
        CancelPenalty: 6360,
        Cashback: 0,
        ChangePenalty: 5300,
        Commission: 0,
        ConvFees: 200,
        DFValue: "0",
        EquivCurrencyCode: "INR",
        ExSeatFare: 0,
        ExSeatFareStatus: false,
        Fare: [
          {
            Amount: 62,
            ChargeCode: "UDF",
            ChargeType: null,
          },
          {
            Amount: 583,
            ChargeCode: "K3.",
            ChargeType: null,
          },
          {
            Amount: 236,
            ChargeCode: "P2.",
            ChargeType: null,
          },
          {
            Amount: 91,
            ChargeCode: "PSF",
            ChargeType: null,
          },
          {
            Amount: 340,
            ChargeCode: "YR",
            ChargeType: null,
          },
        ],
        FareBasisCode: "VL1PYS",
        FareInfoKey: null,
        FareInfoValue: null,
        GDSPnr: null,
        InsuranceAmount: 0,
        IsZeroCancellation: false,
        MarkUP: 0,
        PaxType: 0,
        Refundable: true,
        STF: 0,
        ServiceFee: 0,
        TDS: 0,
        TotalFare: 12632,
        TotalTax: 1312,
        TransactionAmount: 0,
        TransactionFee: 0,
        ZeroCancellationCharge: 0,
        ZeroCancellationValidity: null,
      },
    ],
    RefundAmount: 0,
    RequestedFare: 0,
    SeatCharge: 0,
    TotalConvFees: 200,
    TotalFareWithOutMarkUp: 12632,
    TotalSSRAmount: 0,
    TotalTaxWithOutMarkUp: 1312,
  },
  FareCategory: 0,
  FareIndicator: 0,
  FareRule:
    "CAN-BEF 8760_4:6360|CHG-BEF 8760_4:5300|EMTFee-300|CANCEL-BEF 8760_4:6360|CHANGE-BEF 8760_4:5300",
  Fares: null,
  InsuranceProvider: 0,
  IsBaggageFare: false,
  IsBrandAvailable: true,
  IsBranded: false,
  IsCache: true,
  IsHoldBooking: false,
  IsInsurance: false,
  IsInternational: false,
  IsRoundTrip: false,
  IsSegmentChanged: false,
  IsSpecial: false,
  IsSpecialId: false,
  ItineraryKey: "0h4JDh8rNi7BZDG6L5Q78P9Fqnb27JiPE7m6A48QhDo=",
  JourneyIndex: 0,
  MemoryCreationTime: "/Date(1694510304078+0530)/",
  NearByAirport: false,
  PaxSSRs: null,
  PromoCode: null,
  Remark: null,
  SSDetails: "",
  SSRDetails: null,
  SearchId:
    "114,ADT:BF=11320 Tax=1312,CHD:BF=0 Tax=0,INF:BF=0 Tax=0,DFValue=0,APFV=12632`1312`11320`6360`5300`0`0`VL1PYS``Kgs`15`True`0`0`0`0`,CPFV=,IPFV=,ATB=`UDF:62`K3.:583`P2.:236`PSF:91`YR:340,CTB=,ITB=,TBA=11320,TTA=1312,TFA=12632,RTSearch=0",
  Sessionfilepath: null,
  ShellPNR: null,
  VisaInfo: null,
  ZCStatus: false,
  description: null,
};
