name: Node.js CI/CD with FTP Deployment

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Setup Environment Variables
        run: echo "${{ secrets.env }}" >> .env.prod

      - name: Build Project
        run: |
          npm install --force
          CI=false npm run build --force

      # - name: Cleanup Environment Files
      #   run: rm -rf .env.prod

      # - name: Debug Secrets
      #   run: |
      #     echo "FTP Server: ${{ secrets.ftp_server }}"
      #     echo "FTP Username: ${{ secrets.ftp_username }}"
      #     echo "FTP Password: ***"  # Masking password for security

      # - name: Deploy to FTP Server
      #   uses: SamKirkland/FTP-Deploy-Action@4.3.3
      #   with:
      #     server: ${{ secrets.ftp_server }}
      #     username: ${{ secrets.ftp_username }}
      #     password: ${{ secrets.ftp_password }}
      #     local-dir: ./build/
